triggers:
- repos:
  - jenkins-x
  - rawlingsj
  trusted_org: jenkins-x
  only_org_members: true
- repos:
  - gerrit
  - knative
  - prow
  - jx-build-templates
  - vault-operator
  - openshift-namespace-rbac-chart
  trusted_org: jenkins-x-charts
  only_org_members: true
- repos:
  - core-frontend
  - core-backend
  - haha
  - policy-engine
  - cloudbees-apps
  trusted_org: cloudbees
  only_org_members: true
approve:
- lgtm_acts_as_approve: true
  repos:
  - jenkins-x/jx
  review_acts_as_approve: true
blunderbuss: {}
cat: {}
lgtm:
- repos:
  - jenkins-x/jx
  review_acts_as_lgtm: true
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
heart:
  adorees:
  - jenkins-x-bot
owners: {}
plugins:
  jenkins-x/prow-config:
  - config-updater
  - size
  - shrug
  - skip
  - yuks
  jenkins-x-bot/environment-jenkinsx-dev-production:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x-bot/environment-jenkinsx-dev-staging:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x/jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x/jenkins-x-builders:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-serverless:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-apps/jx-app-gitea:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-apps/jx-app-grafana:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-apps/jx-app-istio:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/vault-operator:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/openshift-namespace-rbac-chart:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/dex:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  rawlingsj/testchart:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-jacoco:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/haha:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/policy-engine:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/cloudbees-apps:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-java-code-quality:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/cloud-environments:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/exposecontroller:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/exposecontroller-service:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/homebrew-jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-image:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-platform:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-docs:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-java-client:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-release-version:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-tutorial:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/knative:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/metrics:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/nexus:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/pipeline-events-addon:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/prow:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/gerrit:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/sso-operator:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/terraform-provider-jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/updatebot:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/vscode-jx-tools:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-extensions:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-spotbugs:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/core-backend:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  cloudbees/core-frontend:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - yuks
  jenkins-x-charts/jx-build-templates:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
requiresig: {}
sigmention: {}
slack: {}
welcome: {}
