triggers:
- repos:
  - jenkins-x/prow-config
approve:
- lgtm_acts_as_approve: true
  repos:
  - jenkins-x-bot/environment-jenkinsx-dev-staging
  - jenkins-x-bot/environment-jenkinsx-dev-production
  review_acts_as_approve: true
blunderbuss: {}
cat: {}
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
heart:
  adorees:
  - jenkins-x-bot
owners: {}
plugins:
  jenkins-x/prow-config:
  - config-updater
  - size
  - shrug
  - skip
  - yuks
  jenkins-x-bot/environment-jenkinsx-dev-production:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x-bot/environment-jenkinsx-dev-staging:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x/jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x/jenkins-x-builders:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-serverless:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/vault-operator:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/dex:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  rawlingsj/testchart:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-jacoco:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-java-code-quality:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/cloud-environments:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/exposecontroller:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/exposecontroller-service:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/homebrew-jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-image:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-platform:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-docs:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-java-client:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-release-version:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-tutorial:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/knative:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/metrics:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/nexus:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/pipeline-events-addon:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/prow:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/sso-operator:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/terraform-provider-jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/updatebot:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/vscode-jx-tools:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/cdx-backend:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/cdx-frontend:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
requiresig: {}
sigmention: {}
slack: {}
welcome:
- repos:
  - jenkins-x/jx
  message_template: "Welcome @{{.AuthorLogin}}! It looks like this is your first PR to {{.Org}}/{{.Repo}} 🎉🎉"

