triggers:
- repos:
  - jenkins-x
  - rawlingsj
  trusted_org: jenkins-x
  only_org_members: true
- repos:
  - jenkins-x-apps
  trusted_org: jenkins-x-apps
  only_org_members: true
- repos:
  - gerrit
  - knative
  - prow
  - jx-build-templates
  - vault-operator
  - athens-proxy
  - openshift-namespace-rbac-chart
  - tekton
  trusted_org: jenkins-x-charts
  only_org_members: true
- repos:
  - core-frontend
  - core-backend
  - core-controllers
  - haha
  - cloudbees-apps
  - cb-app-slack
  trusted_org: cloudbees
  only_org_members: true
- repos:
  - jenkinsci/jx-resources-plugin
  trusted_org: jenkinsci
  only_org_members: true
approve:
- lgtm_acts_as_approve: true
  repos:
  - jenkins-x
  require_self_approval: true
- lgtm_acts_as_approve: true
  repos:
  - jenkins-x-charts
  require_self_approval: true
- lgtm_acts_as_approve: true
  repos:
  - jenkins-x-apps
  require_self_approval: true
- lgtm_acts_as_approve: true
  repos:
  - jenkinsci
  require_self_approval: true
- lgtm_acts_as_approve: true
  repos:
  - cloudbees
  require_self_approval: true
blunderbuss: {}
cat: {}
lgtm:
- repos:
  - jenkins-x/jx
  review_acts_as_lgtm: true
- repos:
  - jenkinsci/jx-resources-plugin
  review_acts_as_lgtm: true
- repos:
  - cloudbees/core-backend
  review_acts_as_lgtm: true
- repos:
  - cloudbees/core-controller
  review_acts_as_lgtm: true
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
heart:
  adorees:
  - jenkins-x-bot

owners: {}
external_plugins:
  jenkins-x/jx:
  - endpoint: http://cb-app-slack
    name: cb-app-slack
  jenkins-x-apps/jx-app-jacoco:
  - endpoint: http://cb-app-slack
    name: cb-app-slack
  jenkins-x-apps/jx-app-cheese:
  - endpoint: http://cb-app-slack
    name: cb-app-slack
plugins:
  jenkins-x/prow-config:
  - config-updater
  - size
  - shrug
  - skip
  - yuks
  jenkins-x-bot/environment-jenkinsx-dev-production:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x-bot/environment-jenkinsx-dev-staging:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x/jx:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  jenkins-x/jenkins-x-builders:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-builders-base-image:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-serverless:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-serverless-filerunner:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/cb-app-slack:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat 
  jenkins-x-apps/jx-app-cheese:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-apps/jx-app-jacoco:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-apps/jx-app-sonarqube:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat 
  jenkins-x-apps/jx-app-gitea:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-apps/jx-app-grafana:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-apps/jx-app-athens:
    - approve
    - heart
    - assign
    - help
    - hold
    - lgtm
    - lifecycle
    - size
    - trigger
    - wip
    - cat
  jenkins-x-apps/jx-app-jenkins:
    - approve
    - heart
    - assign
    - help
    - hold
    - lgtm
    - lifecycle
    - size
    - trigger
    - wip
    - cat
  jenkins-x-charts/vault-operator:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/athens-proxy:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/openshift-namespace-rbac-chart:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/dex:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  rawlingsj/testchart:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/haha:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/cloudbees-apps:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-java-code-quality:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/cloud-environments:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/exposecontroller:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/exposecontroller-service:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/homebrew-jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-image:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-platform:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-docs:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-java-client:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-release-version:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-tutorial:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/knative-build:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  - cat
  jenkins-x-charts/tekton:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/metrics:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/nexus:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/pipeline-events-addon:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/prow:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-charts/gerrit:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/sso-operator:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/terraform-provider-jx:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/updatebot:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/vscode-jx-tools:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jenkins-x-extensions:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/jx-quickstarts-bdd-test-job:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x/ext-spotbugs:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  cloudbees/core-backend:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  cloudbees/core-frontend:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - yuks
  cloudbees/core-controllers:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkins-x-charts/jx-build-templates:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  jenkinsci/jx-resources-plugin:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-images/allure:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-images/xunit-viewer:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
  jenkins-x-images/oauth2_proxy:
  - approve
  - heart
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - cat
requiresig: {}
sigmention: {}
slack: {}
