triggers:
- repos:
  - jenkins-x/prow-config
  - rawlingsj/environment-dukepepper-staging
  - rawlingsj/environment-dukepepper-production
approve:
- lgtm_acts_as_approve: true
  repos:
  - rawlingsj/spring-prow1
  - rawlingsj/environment-dukepepper-staging
  - rawlingsj/environment-dukepepper-production
  review_acts_as_approve: true
blunderbuss: {}
cat: {}
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
heart: {}
owners: {}
plugins:
  rawlingsj/prow-dukepepper-jx-config:
  - config-updater
  - shrug
  - skip
  - yuks
  rawlingsj/spring-prow1:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - heart
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  rawlingsj/environment-dukepepper-staging:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  rawlingsj/environment-dukepepper-production:
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
requiresig: {}
sigmention: {}
slack: {}
welcome: {}
